### ISSUE TITLE
Install error  python3.6 - QGIS 3.0 - OSX 10.13.3 

### ISSUE THREAD

**Issue by AntonioDEM** [KIOS-Research/ImportPhotos#10]
I tried importing IMPORTPHOTO but I verified the problem installing the plugin

Impossibile caricare il plugin 'ImportPhotos' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'exifread' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/__init__.py", line 32, in classFactory
    from .ImportPhotos import ImportPhotos
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 33, in 
    from .MouseClick import MouseClick
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/MouseClick.py", line 31, in 
    import exifread
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'exifread'

Versione Python: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
Versione di QGIS: 3.0.0-Girona Girona, exported 

Percorso Python:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/GEOS.framework/Versions/3B/Python/3.6/site-packages
/Library/Frameworks/GDAL.framework/Versions/2.2/Python/3.6/site-packages
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/Harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by pigreco** [comment]
same error appeared in win 10 64b
I installed the exifread module, now everything works fine.

OSGeo4W64

**Comment by Mariosmsk** [comment]
Try to run the following command on qgis python console:
import pip;   pip.main(['install', 'exifread']);
