### ISSUE TITLE
Issues running Import photo

### ISSUE THREAD

**Issue by M-SOULEZ** [KIOS-Research/ImportPhotos#106]
I'm trying to use import photos but after I successfuly created the point layer I get folling message when trying to print pictures with the click.
The following error message is :
2023-06-29T12:28:12     WARNING    Traceback (most recent call last):
              File "C:/Users/msoulez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImportPhotos\ImportPhotos.py", line 275, in setMouseClickMapTool
              if layer.type() == QgsMapLayerType.VectorLayer and layer.fields().names() == FIELDS:
             NameError: name 'QgsMapLayerType' is not defined
             
I'm running on QGIS 3.4

**Comment by Janne013** [comment]
Since update of plugin 'import photo' in 1/2025 there is an error by using the function 'click photo' : 

2025-01-16T11:25:10     WARNING    Traceback (most recent call last):
              File "C:\Users/theisen.000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImportPhotos\code\MouseClick.py", line 157, in canvasReleaseEvent
              self.photosDLG.add_window_place.setText(name_)
             TypeError: setText(self, a0: Optional[str]): argument 1 has unexpected type 'QDateTime'

QGIS Version 3.34.14
