### ISSUE TITLE
apefil error on ubuntu 18.10

### ISSUE THREAD

**Issue by reginaldc** [KIOS-Research/ImportPhotos#33]
Hi,

I get this error while trying importphotos on ubuntu 18.10:

KeyError: '.apefil' 
Traceback (most recent call last):
  File "/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 368, in ok
    self.extension = self.extension_switch[self.extension]
KeyError: '.apefil'

Python versie: 3.5.2 (default, Oct 11 2018, 08:33:18) [GCC 6.4.0] 
QGIS versie: 3.2.3-Bonn Bonn, 9b17680 

Regards,

**Comment by Mariosmsk** [comment]
Hi @reginaldc ,
`ImportPhotos v1.9` has been released. Check QGIS repository.
Thanks.

**Comment by edips** [comment]
Hi. I also get this error and another error on Ubuntu 20.10. For first error I saved input folder location and output folder location in the same place, second error I saved the locations to different paths. 
```
2020-12-12T15:03:39     WARNING    Traceback (most recent call last):
              File "/home/edip/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 388, in ok
              self.import_photos(self.directoryPhotos, self.outputPath, self.load_style, showMessageHide)
              File "/home/edip/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 456, in import_photos
              self.extension = self.extension_switch[self.extension]
             KeyError: '.apefil'
             
2020-12-12T15:06:53     WARNING    Traceback (most recent call last):
              File "/home/edip/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 388, in ok
              self.import_photos(self.directoryPhotos, self.outputPath, self.load_style, showMessageHide)
              File "/home/edip/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 456, in import_photos
              self.extension = self.extension_switch[self.extension]
             KeyError: '.pefi'
```
