### ISSUE TITLE
Linux: TypeError: 'QVariant' object is not subscriptable 

### ISSUE THREAD

**Issue by d7rk** [KIOS-Research/ImportPhotos#45]
With latest version (2.0) on manjaro, I get the following error when launching:
```
Couldn't load plugin 'ImportPhotos' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/XXX/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/__init__.py", line 33, in classFactory
    return ImportPhotos(iface)
  File "/home/XXX/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 75, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127] 
QGIS version: 3.4.3-Madeira Madeira, exported 

Python Path:
/usr/share/qgis/python
/home/XXX/.local/share/QGIS/QGIS3/profiles/default/python
/home/XXX/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/lib/python3.7/site-packages
/home/XXX/.local/share/QGIS/QGIS3/profiles/default/python
/home/XXX/Shared/Work/APPS/Input/Maps/GIS_main
```

**Comment by Mariosmsk** [comment]
Check out the updated version `ImportPhotos v2.1` . Thanks.
