### ISSUE TITLE
Import work only once per session

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [KIOS-Research/ImportPhotos#65]
Using the plugin on Linux Mint, the import works quite well.
But using it a second time in the same session, it throws this error:
```
KeyError: '.pefi' 
Traceback (most recent call last):
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 388, in ok
    self.import_photos(self.directoryPhotos, self.outputPath, self.load_style, showMessageHide)
  File "/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 456, in import_photos
    self.extension = self.extension_switch[self.extension]
KeyError: '.pefi'


Python-Version: 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
QGIS-Version: 3.8.1-Zanzibar Zanzibar, dcd95cc648 

Python-Pfad:
/usr/share/qgis/python
/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python
/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python
/home/bernd/.local/share/QGIS/QGIS3/profiles/default/python/plugins
.
```

**Comment by rmarzocchi84** [comment]
Same problem encountered

**Comment by rmarzocchi84** [comment]
Sorry.. 
1)  tested on Ubuntu Libnux 18 --> problem) 
2) tested on windows 8 --> It works (no problem)

**Comment by Gui0delp** [comment]
Hey ! I got the same problems when i want to import photos. If i want to import just one photo it work.

I test on:
QGIS 3.10.7-A Coruña
Plugin version: 2.2.2

OS:
macOS Catalina 10.15
Ubuntu 20.04.1 LTS
Windows 10

Always same problem.
