### ISSUE TITLE
QGIS 2.18.17 Linux Mint

### ISSUE THREAD

**Issue by PietsHost** [KIOS-Research/ImportPhotos#9]
NameError: global name 'NSScreen' is not defined 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/user/.qgis2/python/plugins/ImportPhotos/ImportPhotos.py", line 197, in initGui
    self.toolMouseClick = MouseClick(self.iface.mapCanvas(), self)
  File "/home/user/.qgis2/python/plugins/ImportPhotos/MouseClick.py", line 58, in __init__
    self.screensize.append(NSScreen.mainScreen().frame().size.width)
NameError: global name 'NSScreen' is not defined

**Comment by PietsHost** [comment]
Solved in latest Update
